### ISSUE TITLE
AD3 checkit

### ISSUE THREAD

**Issue by cg2wilson** [TeamBasedInquiryLearning/library#370]
I've come across a coding issue in the exercises for AD3. The version of the problem that has a person walking towards a wall away from a light seems like the shadow should always be decreasing, but sometimes the answer key says the shadow is increasing in height. Can someone confirm if this is actually incorrect or if I'm just missing something?

**Comment by StevenClontz** [comment]
I just worked through https://tbil.org/preview/calculus/exercises/#/bank/AD3/2/ and it seems to be right.

But https://tbil.org/preview/calculus/exercises/#/bank/AD3/5/ has the same prompt, but says "up" instead of down.

Looking at the source, I think a correct version of the prompt is already there, just commented out for some reason:

```
<p>
Suppose a person who was <m> {{heightperson}} </m> feet tall was standing between a light on the ground and a wall.  They are <m>{{disttolight}}</m> feet away from the light and <m>{{disttowall}}</m> feet away from the wall.  If they start walking towards the {{persondirection}} at a speed of <m>{{personspeed}}</m> feet/second, how fast would the height of the shadow they cast change and in what direction?
</p>
```

**Comment by cg2wilson** [comment]
I've got a draft request open: https://github.com/TeamBasedInquiryLearning/library/pull/371.
