### ISSUE TITLE
Sort issues calc 1 vs calc 2?

### ISSUE THREAD

**Issue by fragandi** [TeamBasedInquiryLearning/library#62]

**Comment by siwelwerd** [comment]
I think because of the way the source code is organized, we want to keep a "calculus" label for our issues.  Also, there is no consensus across institutions on the dividing line between Calc 1 and Calc 2 (one of the reasons the source is organized like it is).  So maybe just add the relevant ones to your project?

**Comment by fragandi** [comment]
I agree!
