### ISSUE TITLE
Features of the text

### ISSUE THREAD

**Issue by fragandi** [TeamBasedInquiryLearning/library#93]
The TBIL book really needs a section like this [Preface: Features of the Text](https://activecalculus.org/multi/preface-1.html#preface-1)

This would make it much easier to adopt from other folks! 

We can also add a section for instructors that points to joining the TBIL community

**Comment by fragandi** [comment]
@siwelwerd what do you think?

**Comment by siwelwerd** [comment]
I agree some additional front matter could be helpful.  Note that #10 is specifically about the website.

I think I prefer something simple like "Preface for Instructors" and "Preface for Students", as I am not convinced students will read any front matter that doesn't say "For students" (and possibly not even that).

@StevenClontz is it possible to have a top level `common` folder, and then within each book `<xi:include>` a ptx from the top level common file?  Because the prefaces for the three books will overlap quite a bit.   I am imagining e.g. writing one section on connecting to the TBIL community, and then in each book something like  `<xi:include href="../../../common/source/meta/community.ptx">`

**Comment by StevenClontz** [comment]
> @StevenClontz is it possible to have a top level `common` folder, and then within each book `<xi:include>` a ptx from the top level common file? Because the prefaces for the three books will overlap quite a bit. I am imagining e.g. writing one section on connecting to the TBIL community, and then in each book something like `<xi:include href="../../../common/source/meta/community.ptx"/>`

It is possible, and sensible.

**Comment by fragandi** [comment]
A first brainstorm in this PR https://github.com/TeamBasedInquiryLearning/library/pull/109

**Comment by StevenClontz** [comment]
I think this is completed, but please re-open if not (particularly if there's work to do before publishing 2024 edition)
